"""added saved boolean attribute to flashcards

Revision ID: 396e7e8ca205
Revises: 6cdbfa2ba865
Create Date: 2023-11-27 12:46:13.209565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396e7e8ca205'
down_revision = '6cdbfa2ba865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sets', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_column('saved')

    # ### end Alembic commands ###
