"""renaming question and answer attributes to term and definition respectively

Revision ID: 6cdbfa2ba865
Revises: e7b2d266b505
Create Date: 2023-11-16 12:52:08.856711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdbfa2ba865'
down_revision = 'e7b2d266b505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        bind = op.get_bind()
        inspector = sa.inspect(bind)
        if "_alembic_tmp_flashcards" in inspector.get_table_names():
            op.drop_table("_alembic_tmp_flashcards")

        batch_op.add_column(sa.Column('term', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('definition', sa.String(), nullable=False))
        batch_op.drop_column('answer')
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('definition')
        batch_op.drop_column('term')

    # ### end Alembic commands ###
